name: Edgeserver Upload
author: Lucemans
description: Upload folder to edgeserver.io
inputs:
  server:
    description: 'URL of Edgeserver Instance'
    required: false
    default: 'api.edgeserver.io'
  app_id:
    description: 'ID of the App to Deploy to'
    required: true
  token:
    description: 'Auth Token to Access Edgeserver'
    required: true
  directory:
    description: 'Directory to upload'
    default: 'dist'
    required: false
runs:
  using: 'node16'
  main: 'main.js'
branding:
  color: yellow
  icon: upload-cloud